services:
  - type: web
    name: python-backend-api
    env: python
    pythonVersion: 3.12.3
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
